ARG GOLANG_VER=1.18.2

FROM --platform=${BUILDPLATFORM:-linux/amd64} golang:${GOLANG_VER} AS build

ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

WORKDIR /app
COPY src/. .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags="-w -s" -o web-app \
    && chmod a+x web-app

#######
FROM --platform=${TARGETPLATFORM:-linux/amd64} alpine:3.20.2

RUN apk update && apk upgrade && apk cache purge
RUN adduser --no-create-home --disabled-password web-app
USER web-app
WORKDIR /app
COPY --from=build /app/web-app /app/web-app
COPY --from=build /app/*.gohtml /app/
ENTRYPOINT ["/app/web-app"]
